apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sre-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0" 
data:
  DATABASE_URL: "{{ .Values.env.DATABASE_URL }}"
  PHX_HOST: "{{ .Values.env.PHX_HOST }}"
  SECRET_KEY_BASE: "{{ .Values.env.SECRET_KEY_BASE }}"
  POOL_SIZE: "{{ .Values.env.POOL_SIZE }}"
  PORT: "{{ .Values.env.PORT }}"
