apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sre-app.fullname" . }}
  labels:
    app: {{ include "sre-app.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sre-app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "sre-app.fullname" . }}
    spec:
      initContainers:
        - name: wait-for-migration
          image: bitnami/kubectl:latest
          command: 
            - "/bin/sh"
            - "-c"
            - |
              until kubectl get job {{ include "sre-app.fullname" . }}-migrate -n {{ .Release.Namespace }} -o jsonpath="{.status.succeeded}" | grep -q 1; do 
                echo "waiting for migration"; 
                sleep 3; 
              done
      containers:
        - name: {{ include "sre-app.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: {{ include "sre-app.fullname" . }}-config
            - secretRef:
                name: {{ include "sre-app.fullname" . }}-secrets
          ports:
            - name: http
              containerPort: 4000
          livenessProbe:
            {{- if .Values.livenessProbe }}
            {{- toYaml .Values.livenessProbe | nindent 12 }}
            {{- end }}
          readinessProbe:
            {{- if .Values.readinessProbe }}
            {{- toYaml .Values.readinessProbe | nindent 12 }}
            {{- end }}