apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sre-app.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  SECRET_KEY_BASE: {{ .Values.secrets.SECRET_KEY_BASE | b64enc }}