apiVersion: v1
kind: Service
metadata:
  name: sre-app
spec:
  type: "{{ .Values.service.type | default "ClusterIP" }}"
  selector:
    app: sre-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: 4000